# Generated by Django 5.2.8 on 2025-11-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_branch_alter_sale_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Tarjeta Crédito'), ('transferencia', 'Transferencia'), ('debito', 'Tarjeta Débito')], default='efectivo', max_length=20),
        ),
    ]
