# Generated by Django 5.2.8 on 2025-12-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_online_default',
            field=models.BooleanField(default=False, help_text='Si está marcada, esta sucursal se usa para los pedidos de la tienda online.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
