# Generated by Django 5.2.8 on 2025-11-30 03:40

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_created_at_user_default_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT chileno, ej: 12345678-9', max_length=12, null=True, validators=[core.validators.validate_rut]),
        ),
    ]
